WebApp/WebApp/Controllers/CommentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebCollections.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IUserService _userService;
        private readonly IItemService _itemService;


        public CommentController(ICommentService commentService,
            IUserService userService,
            IItemService itemService)
        {
            _commentService = commentService;
            _userService = userService;
            _itemService = itemService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Get(int id)
        {
            MapperConfiguration config = new MapperConfiguration(
                cfg => cfg.CreateMap<Comment, CommentModel>());
            Mapper mapper = new Mapper(config);
            var comments = mapper.Map<List<CommentModel>>(
               await _commentService.Get(id));
            return PartialView("_GetByItem.cshtml", comments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CommentModel comment)
        {
            var user = await _userService.FindById(
                User.FindFirstValue(ClaimTypes.NameIdentifier));
            var newCom = new Comment
            {
                CreatedDate = DateTime.Now,
                Text = comment.Text,
                Items = await _itemService
                .FindById(comment.ItemId),
                User = user,
            };
            await _commentService.Create(newCom);
            return RedirectToAction("GetById","Item", new { id = comment.ItemId });
        }
    }
}

WebApp/WebApp/Views/Comment/Get.cshtml
@model IEnumerable<WebApp.Models.CommentModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApp/WebApp/Views/Comment/_Create.cshtml
@model WebApp.Models.CommentModel

<div class="panel panel-info">
    <div class="panel-heading">
        Comments:
    </div>
    <form asp-action="Create" asp-controller="Comment" method="post">
        <div class="panel-body comments">
            <textarea asp-for="Text" type="text" class="form-control" placeholder="Create your comment" rows="5"></textarea></>
            <br>
            <input asp-for="ItemId" hidden value="@Model.ItemId">
            <button type="submit" class="btn btn-primary">Send</button>
            <div class="clearfix"></div>
        </div>
    </form>
</div>

WebApp/WebApp/Views/Comment/_GetByItem.cshtml
 @model List<CommentModel>

@foreach (var com in Model.ToList())
{
    <hr>
    <ul class="media-list">
        <li class="media">
            <div class="comment">
                <div class="media-body">
                    <strong class="text-success">@com.User.UserName</strong>
                    <span class="text-muted">
                        <small class="text-muted"> @com.CreatedDate.ToLongDateString()</small>
                    </span>
                    <p>
                        @com.Text
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </li>
    </ul>
}