WebApp/WebApp/Controllers/ItemController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebCollections.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;
        private readonly IUserCollectionService _userCollService;
        private readonly IPropService<PropertyInt> _intService;
        private readonly IPropService<PropertyBool> _boolService;
        private readonly IPropService<PropertyString> _strService;
        private readonly IPropService<PropertyText> _textService;
        private readonly ICommentService _commentService;

        public ItemController(IItemService itemService,
            IUserCollectionService userCollService,
            IPropService<PropertyInt> intService,
            IPropService<PropertyBool> boolService,
            IPropService<PropertyString> strService,
            IPropService<PropertyText> textService,
            ICommentService commentService)
        {
            _itemService = itemService;
            _userCollService = userCollService;
            _intService = intService;
            _boolService = boolService;
            _strService = strService;
            _textService = textService;
            _commentService = commentService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Get(UserCollection coll)
        {
            var it = await _itemService.GetColl(coll.Id);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Item, ItemModel>());
            var mapper = new Mapper(config);
            var items = mapper.Map<List<ItemModel>>(it);
            int i = 0;
            foreach (var item in items.ToList())
            {
                item.UserCollId = coll.Id;
                item.PropInt = it[i].PropInts?.ToList();
                item.PropBools = it[i].PropBools?.ToList();
                item.PropStr = it[i].PropStrs?.ToList();
                item.PropText = it[i].PropTexts?.ToList();
                item.Tags = it[i].Tags?.ToList();
                item.UserId = it.First().UserCollection.User.Id;
                i++;
            }
            var itemsModel = new CollItemsModel() { CollItemId = coll.Id, Items = items, UserId = coll.UserId };
            return View(itemsModel);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var propInt = await _intService.Get(id);
            var propStr = await _strService.Get(id);
            var propBool = await _boolService.Get(id);
            var propText = await _textService.Get(id);

            var model = new ItemModel()
            {
                UserCollId = id,
                PropInt = propInt,
                PropStr = propStr,
                PropBools = propBool,
                PropText = propText,
            };
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(ItemModel item)  

        {
            char[] delimiterChars = { ' ', ',', '.', ':' };
            string text = item.TagText;
            var newTags = new List<ItemTag>();
            if (text != null) 
            {
                string[] words = text.Split(delimiterChars, StringSplitOptions.RemoveEmptyEntries);

                foreach (var i in words)
                {
                    newTags.Add(new ItemTag { Text = i.ToLower() });
                }
            }
            var coll = await _userCollService
                .FindById(item.UserCollId);

            var newItem = new Item
            {
                Name = item.Name,
                CreateData = DateTime.Now,
                UserCollection = coll,
                PropInts = item.PropInt,
                PropStrs = item.PropStr,
                PropBools = item.PropBools,
                PropTexts = item.PropText,
                Tags = newTags,
            };
            await _itemService.Create(newItem);
            return RedirectToAction("Get", coll);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(ItemModel model)
        {

            var item = await _itemService.FindById(model.Id);
            if (item == null)
            {
                return View("Error");
            }
            else
            {
                var id = await _userCollService.FindById(model.UserCollId);
                await _itemService.RemoveAsync(item);
                return RedirectToAction("Get", "Item", id);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            var it = await _itemService.FindById(id);

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Item, ItemModel>());
            var mapper = new Mapper(config);
            var item = mapper.Map<ItemModel>(it);

            item.PropInt = it.PropInts?.ToList();
            item.PropBools = it.PropBools?.ToList();
            item.PropStr = it.PropStrs?.ToList();
            item.PropText = it.PropTexts?.ToList();
            item.Likes = it.Likes?.ToList();
            item.Tags = it.Tags?.ToList();

            return View(item);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditItem(int Id, int UserCollId)
        {
            var it = await _itemService.FindById(Id);

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Item, ItemModel>());
            var mapper = new Mapper(config);
            var item = mapper.Map<ItemModel>(it);

            item.PropInt = it.PropInts?.ToList();
            item.PropBools = it.PropBools?.ToList();
            item.PropStr = it.PropStrs?.ToList();
            item.PropText = it.PropTexts?.ToList();
            item.Tags = it.Tags?.ToList();
            item.UserCollId = UserCollId;

            return View(item);
        }  

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditItem(ItemModel model)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<ItemModel, Item>());
            var mapper = new Mapper(config);
            var newitem = mapper.Map<Item>(model);

            newitem.PropBools = model.PropBools?.ToList();
            newitem.PropInts = model.PropInt?.ToList();
            newitem.PropStrs = model.PropStr?.ToList();
            newitem.PropTexts = model.PropText?.ToList();
            newitem.Tags = model.Tags?.ToList();

            await _itemService.Update(newitem);
            return RedirectToAction("GetById", model);
        }
    }
}

WebApp/WebApp/Controllers/LikeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebCollections.Controllers
{
    [Authorize]
    public class LikeController : Controller
    {
        private readonly ILikeService _likeService;
        private readonly IUserService _userService;
        private readonly IItemService _itemService;
        public LikeController(ILikeService likeService,
            IUserService userService,
            IItemService itemService)
        {
            _likeService = likeService;
            _userService = userService;
            _itemService = itemService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetByItem(int id)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<ItemLike, LikeModel>());
            var mapper = new Mapper(config);
            var item = mapper.Map<LikeModel>(await _likeService.FindById(id));
            return PartialView(item);
        }

        public async Task<IActionResult> AddLike(int ItemId)
        {
            var actionResult = false;
            var result = false;
            var user = await _userService.FindById(
                User.FindFirstValue(ClaimTypes.NameIdentifier));
            var like = await _likeService.Get(ItemId);

            foreach (var item in like.ToList())
            {
                if (item.User.Id == user.Id)
                {
                    result = true;
                    await _likeService.RemoveAsync(item);
                    actionResult = true;
                }
            }
            if (result == false)
            {
                var newLike = new ItemLike()
                {
                    Item = await _itemService.FindById(ItemId),
                    User = user,
                    CreatedDate = DateTime.Now,
                };
                await _likeService.Create(newLike);
                actionResult = true;
            }
            return Json(actionResult);
        }
    }
}

WebApp/WebApp/Controllers/TagController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers
{
    //[Authorize]
    public class TagController : Controller
    {
        private readonly ITagService _tagService;
        private readonly IItemService _itemService;

        public TagController(ITagService tagService, IItemService itemService)
        {
            _tagService = tagService;
            _itemService = itemService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetTags()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<ItemTag, TagModel>());
            var mapper = new Mapper(config);
            var tags = mapper.Map<List<TagModel>>(_tagService.Get());

            return View(tags);
        }

        [HttpGet]
        public ActionResult AutoComplete(string term)
        {
            var tags = new List<string>();
            if (term != null)
            {
                tags = _tagService.Get()
                    .Where(p => p.Text.Contains(term))
                    .Select(p => p.Text).ToList();
            }

            return Json(tags);
        }

        [HttpGet]
        public async Task<IActionResult> AddTags()
        { return View(); }


        [HttpPost]
        public async Task<IActionResult> AddTags(TagModel tag)
        {
            char[] delimiterChars = { ' ', ',', '.', ':' };
            string text = tag.Text;
            string[] words = text.Split(delimiterChars, StringSplitOptions.RemoveEmptyEntries);

            var newTags = new List<ItemTag>();
            foreach (var i in words)
            {
                newTags.Add(new ItemTag { Text = i.ToLower() });
            }

            foreach (var i in newTags)
            { await _tagService.Create(i); }
            return View();
        }

    }
}

WebApp/WebApp/Views/Item/Create.cshtml
@model WebApp.Models.ItemModel

@{
    ViewData["Title"] = "Create";
}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>

<h1>Create</h1>

<h4>New Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Item" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            @for (var i = 0; i < Model.PropInt.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropInt[i].Name">@Model.PropInt[i].Name</label>
                    <input asp-for="PropInt[i].Value" class="form-control" />
                    <span asp-validation-for="PropInt[i].Value" class="text-danger"></span>
                    <input asp-for="PropInt[i].Name" hidden value="@Model.PropInt[i].Name" />
                </div>
            }

            @for (var i = 0; i < Model.PropStr.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropStr[i].Name">@Model.PropStr[i].Name</label>
                    <input asp-for="PropStr[i].Value" class="form-control" />
                    <span asp-validation-for="PropStr[i].Value" class="text-danger"></span>
                    <input asp-for="PropStr[i].Name" hidden value="@Model.PropStr[i].Name" />
                </div>
            }
            @for (var i = 0; i < Model.PropBools.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropBools[i].Name">@Model.PropBools[i].Name</label>

                    @*<input asp-for="PropBools[i].Value" class="form-control" />*@

                    <div class="form-check">
                        <input asp-for="PropBools[i].Value" class="form-check-input" type="radio" id="true" value="@true" checked>
                        <label class="form-check-label" for="true">
                            True
                        </label>
                    </div>
                    <div class="form-check">
                        <input asp-for="PropBools[i].Value" class="form-check-input" type="radio" id="false" value="@false">
                        <label class="form-check-label" for="false">
                            False
                        </label>
                    </div>

                    <span asp-validation-for="PropBools[i].Value" class="text-danger"></span>
                    <input asp-for="PropBools[i].Name" hidden value="@Model.PropBools[i].Name" />
                </div>
            }
            @for (var i = 0; i < Model.PropText.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropText[i].Name">@Model.PropText[i].Name</label>
                    <textarea asp-for="PropText[i].Value" class="form-control"></textarea>
                    <span asp-validation-for="PropText[i].Value" class="text-danger"></span>
                    <input asp-for="PropText[i].Name" hidden value="@Model.PropText[i].Name" />
                </div>
            }

            <div class="mb-3">
                <input asp-for="TagText" type="text" class="form-control" id="inputTags" placeholder="Add tag:">
            </div>
            <div class="form-group">
                <input asp-for="UserCollId" hidden class="form-control" value="@Model.UserCollId" />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Get" asp-route-id="@Model.UserCollId">Back to List</a>
</div>




@section Scripts {

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(document).ready(function () {

         $(function () {

        function split(val) {
            return val.split(/,\s*/);
        }
        function extractLast(term) {
            return split(term).pop();
        }

        $("#inputTags")
      // don't navigate away from the field on tab when selecting an item
      .on("keydown", function (event) {
          if (event.keyCode === $.ui.keyCode.TAB &&
              $(this).autocomplete("instance").menu.active) {
              event.preventDefault();
          }
      })
        .autocomplete({
            minLength: 0,
            source: function (request, response) {
                $.getJSON('@Url.Action("AutoComplete","Tag")',
                {
                    term: extractLast(request.term)
                }, response);
            },
            focus: function () {
                // prevent value inserted on focus
                return false;
            },
            select: function (event, ui) {
                var terms = split(this.value);
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push(ui.item.value);
                // add placeholder to get the comma-and-space at the end
                terms.push("");
                this.value = terms.join(", ");
                return false;
            }
        });
    })
    });
</script>

    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

WebApp/WebApp/Views/Item/EditItem.cshtml
@model WebApp.Models.ItemModel

@{
    ViewData["Title"] = "Create";
}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>

<h1>Edit item</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditItem" asp-controller="Item" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            @for (var i = 0; i < Model.PropInt.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropInt[i].Name">@Model.PropInt[i].Name</label>
                    <input asp-for="PropInt[i].Value" class="form-control" value="@Model.PropInt[i].Value"/>
                    <span asp-validation-for="PropInt[i].Value" class="text-danger"></span>
                    <input asp-for="PropInt[i].Name" hidden value="@Model.PropInt[i].Name" />
                    <input asp-for="PropInt[i].Id" hidden value="@Model.PropInt[i].Id" />
                </div>
            }

            @for (var i = 0; i < Model.PropStr.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropStr[i].Name">@Model.PropStr[i].Name</label>
                    <input asp-for="PropStr[i].Value" class="form-control" value="@Model.PropStr[i].Value"/>
                    <span asp-validation-for="PropStr[i].Value" class="text-danger"></span>
                    <input asp-for="PropStr[i].Name" hidden value="@Model.PropStr[i].Name" />
                     <input asp-for="PropStr[i].Id" hidden value="@Model.PropStr[i].Id" />
                </div>
            }
            @for (var i = 0; i < Model.PropBools.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropBools[i].Name">@Model.PropBools[i].Name</label>
                    <input asp-for="PropBools[i].Value" class="form-control" value="@Model.PropBools[i].Value"/>
                    <span asp-validation-for="PropBools[i].Value" class="text-danger"></span>
                    <input asp-for="PropBools[i].Name" hidden value="@Model.PropBools[i].Name" />
                    <input asp-for="PropBools[i].Id" hidden value="@Model.PropBools[i].Id" />
                </div>
            }
            @for (var i = 0; i < Model.PropText.Count; i++)
            {
                <div class="mb-3">
                    <label asp-for="PropText[i].Name">@Model.PropText[i].Name</label>
                    <textarea asp-for="PropText[i].Value" class="form-control" value="@Model.PropText[i].Value"></textarea>
                    <span asp-validation-for="PropText[i].Value" class="text-danger"></span>
                    <input asp-for="PropText[i].Name" hidden value="@Model.PropText[i].Name" />
                    <input asp-for="PropText[i].Id" hidden value="@Model.PropText[i].Id" />
                </div>
            }

            <div class="mb-3">
                <input asp-for="TagText" type="text" class="form-control" id="inputTags" placeholder="Add tag:">
            </div>
            <div class="form-group">
                <input asp-for="UserCollId" hidden class="form-control" value="@Model.UserCollId" />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Get" asp-route-id="@Model.UserCollId">Back to List</a>
</div>


@section Scripts {
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
     $(document).ready(function () {

          $(function () {

         function split(val) {
             return val.split(/,\s*/);
         }
         function extractLast(term) {
             return split(term).pop();
         }

         $("#inputTags")
       // don't navigate away from the field on tab when selecting an item
       .on("keydown", function (event) {
           if (event.keyCode === $.ui.keyCode.TAB &&
               $(this).autocomplete("instance").menu.active) {
               event.preventDefault();
           }
       })
         .autocomplete({
             minLength: 0,
             source: function (request, response) {
                 $.getJSON('@Url.Action("AutoComplete","Tag")',
                 {
                     term: extractLast(request.term)
                 }, response);
             },
             focus: function () {
                 // prevent value inserted on focus
                 return false;
             },
             select: function (event, ui) {
                 var terms = split(this.value);
                 // remove the current input
                 terms.pop();
                 // add the selected item
                 terms.push(ui.item.value);
                 // add placeholder to get the comma-and-space at the end
                 terms.push("");
                 this.value = terms.join(", ");
                 return false;
             }
         });
     })
     });
</script>

    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

WebApp/WebApp/Views/Item/Get.cshtml
@using System.Security.Claims
@using WebApp.Models
@model CollItemsModel

<head>
    @*<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>*@
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>


 @if (User.IsInRole("Admin") || Model.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
{
    <a type="button" class="btn btn-primary" asp-action="Create" asp-controller="Item" asp-route-id="@Model.CollItemId">Add item</a>
    <br>
}
<div class="container">
    <div class="col-sm-12">
        @foreach (var item in Model.Items.ToList())
        {
            <div class="bs-calltoaction bs-calltoaction-info">
                <div class="row">
                    <div class="col-md-9 cta-contents">
                        <h1 class="cta-title">@item.Name</h1>
                        <div class="cta-desc">
                            @foreach (var prop in item.PropInt.ToList())
                            {
                                <p>@prop.Name : @prop.Value</p>
                            }
                            @foreach (var prop in item.PropStr.ToList())
                            {
                                <p>@prop.Name : @prop.Value</p>
                            }
                            @foreach (var prop in item.PropBools.ToList())
                            {
                                <p>@prop.Name : @prop.Value</p>
                            }
                            @foreach (var prop in item.PropText.ToList())
                            {
                                <p>@prop.Name : @prop.Value</p>
                            }
                        </div>
                        <p>Tags:</p>
                        <div class="col-xs-12" style="display:inline-block">
                            @foreach (var i in item.Tags.ToList())
                            {
                                <a asp-area="" asp-controller="Home" asp-action="SearchTag" asp-route-search="@i.Text" class="btn btn-secondary mytag">@i.Text</a>
                            }
                        </div>
                    </div>
                    <div class="col-md-3 cta-button">
                        @{
                            var data = new Dictionary<string, string> { { "Id", item.Id.ToString() }, { "UserCollId", Model.CollItemId.ToString() }, { "UserId", item.UserId.ToString() } };
                        }
                        <div class="btn-group-vertical">
                            <a asp-action="GetById" asp-controller="Item" asp-route-id="@item.Id" class="btn btn-lg btn-block btn-info" style="margin-bottom: 5px;">More info</a>
                            
                            @if (@item.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier)|| User.IsInRole("Admin"))
                            {
                                <form asp-action="DeleteItem" asp-all-route-data="data" method="post">
                                <a asp-action="EditItem" asp-all-route-data="data" class="btn btn-lg btn-block btn-info">Edit</a>
                                    <button type="submit" class="btn btn-lg btn-block btn-info" style="width:120.72px">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                        </svg>Delete</button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts{
}

WebApp/WebApp/Views/Item/GetById.cshtml
@using WebApp.Models
@model ItemModel

<div class="card mb-3">
    <div class="card-header">
        <h5 class="card-title">@Model.Name</h5>
    </div>
    <div class="card-body">
        @foreach (var prop in Model.PropInt)
        {
            <p>@prop.Name : @prop.Value</p>
        }
        @foreach (var prop in Model.PropStr)
        {
            <p>@prop.Name : @prop.Value</p>
        }
        @foreach (var prop in Model.PropBools)
        {
            <p>@prop.Name : @prop.Value</p>
        }
        @foreach (var prop in Model.PropText)
        {
            <p>@prop.Name : @prop.Value</p>
        }
    </div>
    <div class="card-footer">
        <p>
            @Model.Likes.Count()
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
            </svg>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="btn btn-default btn-lnk" id="btnLike">Like</a>
                <input type="hidden" id="userId" value="@Model.Id" />
            }
        </p>
        <p>
            Tags:</>
            <div class="col-xs-12" style="display:inline-block">
                @foreach (var i in Model.Tags)
                {
                    <a asp-area="" asp-controller="Home" asp-action="SearchTag" asp-route-search="@i.Text" class="btn btn-secondary mytag">@i.Text</a>
                }
            </div>

            <div class="row">
                <div class="col-md-12">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @await Html.PartialAsync("~/Views/Comment/_Create.cshtml",new WebApp.Models.CommentModel(){ItemId = Model.Id, CollId = Model.UserCollId})
                    }

                    <div class="update">
                        <ul class="media-list allcomments">
                            @foreach (var com in Model.Comments.ToList())
                            {
                                <li class="media">
                                    <div class="comment">
                                        <div class="media-body">
                                            <strong class="text-success">@com.User.UserName</strong>
                                            <span class="text-muted">
                                                <small class="text-muted"> @com.CreatedDate.ToLongDateString()</small>
                                            </span>
                                            <p>
                                                @com.Text
                                            </p>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
    </div>
</div>

@section Scripts
{
<script>
    $(document).ready(function () {

        var a = $("#userId").val();

        $("#btnLike").click(function () {

            $.ajax({
                type: "POST",
                url: "@Url.Action("AddLike", "Like")",
                data:
                {
                    ItemId: a,
                },
                success: function (result) {
                    if(result){window.location.reload();}
                    else{ alert("Error!"); }
                }
            });
        });
    });

    setInterval(()=>{
    $.get(@Model.Id).then(function(html)
    {
        var list = $(".allcomments", html);
        $(".update").html(list);
    });
    },5000);

</script>
}