WebApp/WebApp/Controllers/RoleController.cs
using AutoMapper;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;
using Westwind.AspNetCore.Markdown;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<Data.Models.User> _userManager;
        private readonly IThemeService _themeService;
        private readonly IUserCollectionService _userCollService;
        private readonly IUserService _userService;


        public RoleController(RoleManager<IdentityRole> roleManager,
            UserManager<Data.Models.User> userManager,
            IThemeService themeService,
            IUserCollectionService userCollService,
            IUserService userService)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _themeService = themeService;
            _userCollService = userCollService;
            _userService = userService;
        }

        public IActionResult Index() => View(_roleManager.Roles.ToList());
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult UserList()
        {
            MapperConfiguration config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserModel>());
            Mapper mapper = new Mapper(config);
            var users = mapper.Map<List<UserModel>>(_userManager.Users.ToList());
            return View(users);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var model = new ChangeRoleModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                var allRoles = _roleManager.Roles.ToList();

                var addedRoles = roles.Except(userRoles);

                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> CreateColl(string id)
        {
            var coll = new CollectionModel();
            coll.Themes = _themeService.Get();
            coll.UserId = id;
            return View(coll);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateColl(CollectionModel userColl)
        {
            if (userColl.UserId == null)
            {
                return View("~/Areas/Identity/Pages/Account/Login.cshtml");
            }

            var file = userColl.ImageData;
            var propInt = new List<PropertyInt>(3);
            var propStr = new List<PropertyString>(3);
            var propBool = new List<PropertyBool>(3);
            var propText = new List<PropertyText>(3);

            foreach (var i in userColl.PropIntName)
            {
                if (i != null)
                    propInt.Add(new PropertyInt()
                    { Name = i });
            }

            foreach (var i in userColl.PropStrName)
            {
                if (i != null)
                    propStr.Add(new PropertyString()
                    { Name = i });
            }

            foreach (var i in userColl.PropBoolName)
            {
                if (i != null)
                    propBool.Add(new PropertyBool()
                    { Name = i });
            }

            foreach (var i in userColl.PropTextName)
            {
                if (i != null)
                    propText.Add(new PropertyText()
                    { Name = i });
            }

            string connectionString = Environment.GetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING");

            var blobServiceClient = new BlobServiceClient(connectionString);
            var containerClient = blobServiceClient.GetBlobContainerClient(userColl.UserId);
            await containerClient.CreateIfNotExistsAsync(PublicAccessType.Blob);

            var files = new List<string>();
            var fileName = file.FileName;
            await foreach (var blob in containerClient.GetBlobsAsync())
            {
                files.Add(blob.Name);
            }
            while (files.Contains(file.FileName))
            {
                fileName = "newFile_" + file.FileName;
            }

            var blobClient = containerClient.GetBlobClient(fileName);

            var httpHeaders = new BlobHttpHeaders()
            {
                ContentType = file.ContentType
            };

            await blobClient.UploadAsync(file.OpenReadStream(), httpHeaders);

            var coll = new UserCollection
            {
                Theme = await _themeService.FindById(userColl.ThemeId),
                Name = userColl.Name,
                Description = Markdown.Parse(userColl.Description),
                Image = blobClient.Uri.ToString(),
                User = await _userManager.FindByIdAsync(userColl.UserId),
                PropBools = propBool,
                PropInts = propInt,
                PropStrs = propStr,
                PropTexts = propText,
            };
            await _userCollService.Create(coll);
            return RedirectToAction("Create", "Item", coll);
        }
        
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Block(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                user.LockoutEnd = DateTime.MaxValue;
                await _userService.Update(user);
                await _userManager.UpdateSecurityStampAsync(user);
                await _userService.Update(user);
                return RedirectToAction("Get", "User");
            }
            return NotFound();
        }
        
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Unblock(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                user.LockoutEnd = null;
                await _userService.Update(user);
                return RedirectToAction("Get", "User");
            }
            return NotFound();
        }
    }
}

WebApp/WebApp/Controllers/ThemeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ThemeController : Controller
    {
        private readonly IThemeService _themeService;

        public ThemeController(IThemeService themeService)
        {
            _themeService = themeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetThemes()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Theme, ThemeModel>());
            var mapper = new Mapper(config);
            
            var items = mapper.Map<List<ThemeModel>>(_themeService.Get());

            return View(items);
        }

        [HttpGet]
        public async Task<IActionResult> CreateTheme()
        {
            return PartialView("_CreateTheme");
        }



        [HttpPost]
        public async Task<IActionResult> CreateTheme(ThemeModel theme)
        {

            var item = new Theme() {Name = theme.Name };
            
            await _themeService.Create(item);

            return RedirectToAction("GetThemes");
        }


    }
}

WebApp/WebApp/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebCollections.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Get()
        {
            MapperConfiguration config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserModel>());
            Mapper mapper = new Mapper(config);
            var users = mapper.Map<List<UserModel>>(_userService.Get());
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserModel model)
        {
            var user = await _userService.FindById(model.Id);
            if (user == null)
            {
                return View("Error");
            }
            else
            {
                user.UserName = model.UserName;
                user.Email = model.Email;
                await _userService.Update(user);
                return RedirectToAction("Get");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userService.FindById(id);
            if (user == null)
            {
                return View("Error");
            }
            var config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserModel>());
            var mapper = new Mapper(config);
            var userModel = mapper.Map<UserModel>(await _userService.Update(user));
            return View(userModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(UserModel model)
        {
            var user = await _userService.FindById(model.Id);
            if (user == null)
            {
                return View("Error");
            }
            else
            {
                await _userService.RemoveAsync(user);
                return RedirectToAction("Get");
            }
        }
    }
}

WebApp/WebApp/Views/User/EditUser.cshtml
@model UserModel

@{
    ViewBag.Title = "Edit User";
}

<h1>Edit User: @Model.UserName</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UserName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UserName" class="form-control">
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary=All class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="Get" class="btn btn-primary">Cancel</a>
        </div>
    </div>

</form>

WebApp/WebApp/Views/User/Get.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@using WebApp.Models
@model List<UserModel>

<h2>@Localizer["Title"]</h2>
<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item"><a class="nav-link" asp-controller="Role" asp-action="Index">@Localizer["NavRole"]</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="GetThemes" asp-controller="Theme">@Localizer["NavTheme"]</a></li>
        </ul>
    </div>

    <div class="col-md-9">
        @foreach (var user in Model)
        {
            <div class="card mb-3">
                <div class="card-header">Role
                    User Id: @user.Id
                </div>
                <div class="card-body">
                    <h5 class="card-title">@user.UserName</h5>
                </div>
                <div class="card-footer">
                    <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                        <a asp-action="EditUser" asp-controller="User" asp-route-id="@user.Id" class="btn btn-dark">@Localizer["Edit"]</a>
                        <a class="btn btn-dark" asp-action="Edit"  asp-controller="Role" asp-route-userid="@user.Id">@Localizer["Role"]</a>
                        <a class="btn btn-dark" asp-controller="Role" asp-action="Block" asp-route-userid="@user.Id">@Localizer["Block"]</a>
                        <a class="btn btn-dark" asp-controller="Role" asp-action="Unblock" asp-route-userid="@user.Id">@Localizer["Unblock"]</a>
                        <button type="submit" class="btn btn-dark">@Localizer["Del"]</button>
                        <a asp-action="CreateColl" asp-controller="Role" asp-route-id="@user.Id" class="btn btn-dark">@Localizer["Coll"]</a>
                    </form>
                </div>
            </div>
        }
    </div>
</div>