WebApp/WebApp/Controllers/UserCollController.cs
using AutoMapper;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;
using Westwind.AspNetCore.Markdown;

namespace WebCollections.Controllers
{

    public class UserCollController : Controller
    {
        private readonly IUserCollectionService _userCollService;
        private readonly IThemeService _themeService;
        private readonly IUserService _userService;

        public UserCollController(
            IUserCollectionService userCollService,
            IUserService userService,
            IThemeService themeService)
        {
            _userCollService = userCollService;
            _userService = userService;
            _themeService = themeService;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<UserCollection, CollectionModel>());
            var mapper = new Mapper(config);
            var coll = mapper.Map<List<CollectionModel>>(_userCollService.Get());
            return View(coll);
        }

        [HttpGet]
        public async Task<IActionResult> GetColl()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<UserCollection, CollectionModel>());
            var mapper = new Mapper(config);
            var coll = mapper.Map<List<CollectionModel>>(await _userCollService.Get(userId));
            return View("Get", coll);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> CreateColl()
        {
            var coll = new CollectionModel();
            coll.Themes = _themeService.Get();
            return View(coll);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateColl(CollectionModel userColl)
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return View("~/Areas/Identity/Pages/Account/Login.cshtml");
            }

            var file = userColl.ImageData;
            var propInt = new List<PropertyInt>(3);
            var propStr = new List<PropertyString>(3);
            var propBool = new List<PropertyBool>(3);
            var propText = new List<PropertyText>(3);

            foreach (var i in userColl.PropIntName)
            {
                if (i != null)
                    propInt.Add(new PropertyInt()
                    { Name = i });
            }

            foreach (var i in userColl.PropStrName)
            {
                if (i != null)
                    propStr.Add(new PropertyString()
                    { Name = i });
            }

            foreach (var i in userColl.PropBoolName)
            {
                if (i != null)
                    propBool.Add(new PropertyBool()
                    { Name = i });
            }

            foreach (var i in userColl.PropTextName)
            {
                if (i != null)
                    propText.Add(new PropertyText()
                    { Name = i });
            }

            string connectionString = Environment.GetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING");

            var blobServiceClient = new BlobServiceClient(connectionString);
            var containerClient = blobServiceClient.GetBlobContainerClient(userId);
            await containerClient.CreateIfNotExistsAsync(PublicAccessType.Blob);

            var files = new List<string>();
            var fileName = file.FileName;
            await foreach (var blob in containerClient.GetBlobsAsync())
            {
                files.Add(blob.Name);
            }
            while (files.Contains(file.FileName))
            {
                fileName = "newFile_" + file.FileName;
            }

            var blobClient = containerClient.GetBlobClient(fileName);

            var httpHeaders = new BlobHttpHeaders()
            {
                ContentType = file.ContentType
            };

            await blobClient.UploadAsync(file.OpenReadStream(), httpHeaders);

            var coll = new UserCollection
            {
                Theme = await _themeService.FindById(userColl.ThemeId),
                Name = userColl.Name,
                Description = Markdown.Parse(userColl.Description),
                Image = blobClient.Uri.ToString(),
                User = await _userService.FindById(userId),
                PropBools = propBool,
                PropInts = propInt,
                PropStrs = propStr,
                PropTexts = propText,
            };
            await _userCollService.Create(coll);
            return RedirectToAction("Create", "Item", coll);
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id, string UserId)
        {
            var coll = await _userCollService.FindById(id);
            coll.UserId = UserId;
            return RedirectToAction("Get", "Item", coll);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteColl(CollectionModel model)
        {
            var coll = await _userCollService.FindById(model.Id);
            if (coll == null)
            {
                return View("Error");
            }
            else
            {
                await _userCollService.RemoveAsync(coll);
                return RedirectToAction("Get");
            }
        }

        public ActionResult GetCollSort(int? theme)
        
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<UserCollection, CollectionModel>());
            var mapper = new Mapper(config);
            var coll = mapper.Map<List<CollectionModel>>(_userCollService.Get());

            if (theme != null && theme != 0)
            {
                coll = coll.Where(p => p.ThemeId == theme).ToList();
            }

            var themes = _themeService.Get();
            // устанавливаем начальный элемент, который позволит выбрать всех
            themes.Insert(0, new Theme { Id = 0, Name = "All",});

            var viewModel = new SortCollModel
            {
                Collections = coll.ToList(),
                Themes = new SelectList(themes, "Id", "Name"),
            };

            return View(viewModel);
        }






    }
}

WebApp/WebApp/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data.Models;
using WebApp.Models;
using WebApp.Services.Interfaces;

namespace WebCollections.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Get()
        {
            MapperConfiguration config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserModel>());
            Mapper mapper = new Mapper(config);
            var users = mapper.Map<List<UserModel>>(_userService.Get());
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserModel model)
        {
            var user = await _userService.FindById(model.Id);
            if (user == null)
            {
                return View("Error");
            }
            else
            {
                user.UserName = model.UserName;
                user.Email = model.Email;
                await _userService.Update(user);
                return RedirectToAction("Get");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userService.FindById(id);
            if (user == null)
            {
                return View("Error");
            }
            var config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserModel>());
            var mapper = new Mapper(config);
            var userModel = mapper.Map<UserModel>(await _userService.Update(user));
            return View(userModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(UserModel model)
        {
            var user = await _userService.FindById(model.Id);
            if (user == null)
            {
                return View("Error");
            }
            else
            {
                await _userService.RemoveAsync(user);
                return RedirectToAction("Get");
            }
        }
    }
}

WebApp/WebApp/Views/UserColl/CreateColl.cshtml
@using WebApp.Models
@model CollectionModel

<head>
    <link rel="stylesheet" href="~/css/site.css">
</head>

<body>
    <div class="container" style="min-height:800px">
        <form asp-action="CreateColl" asp-controller="UserColl" method="post" enctype="multipart/form-data" class="row">
            <h2 class="text-center">@Localizer["Title"]</h2>
            <hr />
            <div class="col align-self-center">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row g-3">
                    <div class="col-md-6">
                        <label asp-for="Name" class="form-label">@Localizer["Name"]:</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">
                        <label asp-for="Theme" class="form-label">@Localizer["Theme"]:</label>
                        <select asp-for="ThemeId" class="form-control form-select">
                            @foreach (var theme in Model.Themes)
                            {
                                <option value="@theme.Id">@theme.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="mb-3">
                    <label asp-for="Description" class="form-label">@Localizer["Des"]:</label>
                    <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">@Localizer["Image"]:</label>
                            <div class="preview-zone hidden">
                                <div class="box box-solid">
                                    <div class="box-header with-border">
                                        <div><b>@Localizer["Preview"]</b></div>
                                        <div class="box-tools pull-right">
                                            <button type="button" class="btn btn-danger btn-xs remove-preview">
                                                <i class="fa fa-times"></i> @Localizer["Reset"]
                                            </button>
                                        </div>
                                    </div>
                                    <div class="box-body"></div>
                                </div>
                            </div>
                            <div class="dropzone-wrapper">
                                <div class="dropzone-desc">
                                    <i class="glyphicon glyphicon-download-alt"></i>
                                    <p>@Localizer["Zone"]</p>
                                </div>
                                <input type="file" name="ImageData" class="dropzone">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <h4>@Localizer["Num"]:</h4>
                <hr />
                @for (var i = 0; i < 3; i++)
                {
                    <div class="mb-3">
                        <input asp-for="PropIntName[i]" class="form-control" placeholder="@Localizer["Property"] @(i+1) @Localizer["Optional"]:"/>
                        <span asp-validation-for="PropIntName[i]" class="text-danger"></span>
                    </div>
                }
                </br>
                <h4>@Localizer["String"]:</h4>
                <hr />
                @for (var i = 0; i < 3; i++)
                {
                    <div class="mb-3">
                        <input asp-for="PropStrName[i]" class="form-control" placeholder="@Localizer["Property"] @(i+1) @Localizer["Optional"]:"/>
                        <span asp-validation-for="PropStrName[i]" class="text-danger"></span>
                    </div>
                }
                </br>
            </div>
            <div class="col">
                <h4>@Localizer["Bool"]:</h4>
                <hr />
                @for (var i = 0; i < 3; i++)
                {
                    <div class="mb-3">
                        <input asp-for="PropBoolName[i]" class="form-control" placeholder="@Localizer["Property"] @(i+1) @Localizer["Optional"]:"/>
                        <span asp-validation-for="PropIntName[i]" class="text-danger"></span>
                    </div>
                }
                </br>
                <h4>@Localizer["Text"]:</h4>
                <hr />
                @for (var i = 0; i < 3; i++)
                {
                    <div class="mb-3">
                        <input asp-for="PropTextName[i]" class="form-control" placeholder="@Localizer["Property"] @(i+1) @Localizer["Optional"]:"/>
                        <span asp-validation-for="PropTextName[i]" class="text-danger"></span>
                    </div>
                }
                </br>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button id="Submit" type="submit" class="btn btn-primary">@Localizer["Create"]</button>
                </div>
            </div>
        </form>

    </div>
</body>

@section Scripts
{
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
@*<script src="function.js"></script>*@

<script>
    function readFile(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
          var htmlPreview =
            '<img width="200" src="' + e.target.result + '" />' +
            '<p>' + input.files[0].name + '</p>';
          var wrapperZone = $(input).parent();
          var previewZone = $(input).parent().parent().find('.preview-zone');
          var boxZone = $(input).parent().parent().find('.preview-zone').find('.box').find('.box-body');

          wrapperZone.removeClass('dragover');
          previewZone.removeClass('hidden');
          boxZone.empty();
          boxZone.append(htmlPreview);
        };

        reader.readAsDataURL(input.files[0]);
      }
    }

    function reset(e) {
      e.wrap('<form>').closest('form').get(0).reset();
      e.unwrap();
    }

    $(".dropzone").change(function() {
      readFile(this);
    });

    $('.dropzone-wrapper').on('dragover', function(e) {
      e.preventDefault();
      e.stopPropagation();
      $(this).addClass('dragover');
    });

    $('.dropzone-wrapper').on('dragleave', function(e) {
      e.preventDefault();
      e.stopPropagation();
      $(this).removeClass('dragover');
    });

    $('.remove-preview').on('click', function() {
      var boxZone = $(this).parents('.preview-zone').find('.box-body');
      var previewZone = $(this).parents('.preview-zone');
      var dropzone = $(this).parents('.form-group').find('.dropzone');
      boxZone.empty();
      previewZone.addClass('hidden');
      reset(dropzone);
    });</script>
<partial name="_ValidationScriptsPartial" />

}

WebApp/WebApp/Views/UserColl/Get.cshtml
@using System.Security.Claims
@using WebApp.Models
@using Westwind.AspNetCore.Markdown
@model List<CollectionModel>

@{
    ViewData["Title"] = "Home page";
}




<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-3 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-3 justify-content">
            @foreach (var coll in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        @{
                            var data = new Dictionary<string, string> { { "UserId", coll.UserId.ToString() }, { "id", coll.Id.ToString() } };
                        }
                        <a asp-action="GetById" asp-controller="UserColl"  asp-all-route-data="data" style="text-decoration: none;">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Items: @coll.Items.Count()</div>
                            <img class="card-img-top" src="@coll.Image" alt="Generic placeholder image" style="max-height:200px">
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">@coll.Name</h5>
                                    <div>@(Markdown.ParseHtmlString(coll.Description.ToString()))</div>
                                    <p class="card-text">Theme: @coll.Theme.Name</p>
                                    <p class="card-text">created by @coll.User.UserName</p>
                                </div>
                            </div>
                        </a>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @if (@coll.User.Id == User.FindFirstValue(ClaimTypes.NameIdentifier) || User.IsInRole("Admin"))
                                {
                                    <div class="card-body">
                                        <form asp-action="DeleteColl" asp-route-id="@coll.Id" method="post" class="row">
                                            <div class="col text-center">
                                                @*<a asp-action="EditColl" asp-controller="User" asp-route-id="@coll.Id" class="btn btn-danger">Edit</a>*@
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</section>
  
@section Scripts
{
}

WebApp/WebApp/Views/UserColl/GetCollSort.cshtml
@using System.Security.Claims
@using WebApp.Models
@using Westwind.AspNetCore.Markdown



@model SortCollModel

@{
    ViewData["Title"] = "Home page";
}

<form method="get" class="row g-3">
    <div class="col-auto">
        <label class="control-label"><h3>@Localizer["Theme"]:</h3></label>
    </div>
    <div class="col-auto">
        <select name="theme" asp-items="Model.Themes" class="form-control"></select>
    </div>
    <div class="col-auto">
        <input type="submit" value="@Localizer["Filter"]" class="btn btn-secondary" />
    </div>
</form>



<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-3 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-3 justify-content">
            @foreach (var coll in Model.Collections)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        @{
                            var data = new Dictionary<string, string> { { "UserId", coll.UserId.ToString() }, { "id", coll.Id.ToString() } };
                        }
                        <a asp-action="GetById" asp-controller="UserColl" asp-all-route-data="data" style="text-decoration: none;">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">@Localizer["Count"]: @coll.Items.Count()</div>
                            <img class="card-img-top" src="@coll.Image" alt="Generic placeholder image" style="max-height:200px">
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">@coll.Name</h5>
                                    <div>@(Markdown.ParseHtmlString(coll.Description.ToString()))</div>
                                    <p class="card-text">@Localizer["Theme"]: @coll.Theme.Name</p>
                                    <p class="card-text">@Localizer["Created"] @coll.User.UserName</p>
                                </div>
                            </div>
                        </a>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                @if (@coll.User.Id == User.FindFirstValue(ClaimTypes.NameIdentifier) || User.IsInRole("Admin"))
                                {
                                    <div class="card-body">
                                        <form asp-action="DeleteColl" asp-route-id="@coll.Id" method="post" class="row">
                                            <div class="col text-center">
                                                @*  <a asp-action="EditColl" asp-controller="User" asp-route-id="@coll.Id" class="btn btn-danger">Edit</a>*@
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</section>

@section Scripts
{
}